### ISSUE TITLE
When running example: Error: ENOENT: no such file or directory, scandir '/{workDir}/node_modules/vike/node/client'

### ISSUE THREAD

**Issue by deslee** [vikejs/vike-cloudflare#52]
When running with the new vike-server changes, i get this error:

```
Server running at http://localhost:3000
Error: ENOENT: no such file or directory, readdir '/home/projects/stackblitz-starters-j3p9onpy/node_modules/client'
    at Module.readdirSync (node:fs:31:17783)
    at Module.totalist (file:///home/projects/stackblitz-starters-j3p9onpy/node_modules/totalist/sync/index.mjs:21:16)
    at serveStatic (file:///home/projects/stackblitz-starters-j3p9onpy/node_modules/@universal-middleware/sirv/dist/chunk-CONFVDKL.js:302:20)
    at serveStaticFiles (file:///home/projects/stackblitz-starters-j3p9onpy/node_modules/vike-server/dist/chunk-Z4F6BVAV.js:81:26)
    at Object.universalMiddlewareHono (file:///home/projects/stackblitz-starters-j3p9onpy/node_modules/@universal-middleware/hono/dist/index.js:52:24)
    at dispatch (file:///home/projects/stackblitz-starters-j3p9onpy/node_modules/hono/dist/compose.js:35:17)
    at Object.universalMiddlewareHono (file:///home/projects/stackblitz-starters-j3p9onpy/node_modules/@universal-middleware/hono/dist/index.js:54:9)
    at dispatch (file:///home/projects/stackblitz-starters-j3p9onpy/node_modules/hono/dist/compose.js:35:17)
    at eval (file:///home/projects/stackblitz-starters-j3p9onpy/node_modules/hono/dist/hono-base.js:209:25)
    at responseViaResponseObject (file:///home/projects/stackblitz-starters-j3p9onpy/node_modules/vike-server/dist/hono/serve.node.js:376:13) {
  errno: -2,
  syscall: 'readdir',
  code: 'ENOENT',
  path: '/home/projects/stackblitz-starters-j3p9onpy/node_modules/client'
}
```

Minimum reproduction: https://stackblitz.com/edit/stackblitz-starters-j3p9onpy?file=package.json

**Comment by magne4000** [comment]
Fixed in `0.2.1`

**Comment by deslee** [comment]
I'm still seeing the issue with 0.2.1

https://stackblitz.com/edit/stackblitz-starters-5fimmqqh?file=package.json

```
Server running at http://localhost:3000
Error: ENOENT: no such file or directory, readdir '/home/projects/stackblitz-starters-5fimmqqh/node_modules/client'
    at Module.readdirSync (node:fs:31:17783)
    at Module.totalist (file:///home/projects/stackblitz-starters-5fimmqqh/node_modules/totalist/sync/index.mjs:21:16)
    at serveStatic (file:///home/projects/stackblitz-starters-5fimmqqh/node_modules/@universal-middleware/sirv/dist/chunk-ZWGVEH2Z.js:324:20)
    at serveStaticFiles (file:///home/projects/stackblitz-starters-5fimmqqh/node_modules/vike-server/dist/chunk-Z4F6BVAV.js:81:26)
    at Object.universalMiddlewareHono (file:///home/projects/stackblitz-starters-5fimmqqh/node_modules/@universal-middleware/hono/dist/index.js:52:24)
    at dispatch (file:///home/projects/stackblitz-starters-5fimmqqh/node_modules/hono/dist/compose.js:35:17)
    at Object.universalMiddlewareHono (file:///home/projects/stackblitz-starters-5fimmqqh/node_modules/@universal-middleware/hono/dist/index.js:54:9)
    at dispatch (file:///home/projects/stackblitz-starters-5fimmqqh/node_modules/hono/dist/compose.js:35:17)
    at eval (file:///home/projects/stackblitz-starters-5fimmqqh/node_modules/hono/dist/hono-base.js:209:25)
    at responseViaResponseObject (file:///home/projects/stackblitz-starters-5fimmqqh/node_modules/vike-server/dist/hono/serve.node.js:376:13) {
  errno: -2,
  syscall: 'readdir',
  code: 'ENOENT',
  path: '/home/projects/stackblitz-starters-5fimmqqh/node_modules/client'
}
```

**Comment by magne4000** [comment]
Fixed in `0.2.2` 🤞
